
    eureka:
    instance:
    prefer-ip-address: true
      client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
      server:
        enableSelfPreservation: false
